routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OrderController;
// use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
});




Route::get('orders/delete/{id}','OrdersController@destroy')->name('order.delete');
Route::get('myOrders', 'OrdersController@myOrders')->name('orders.myOrders')->middleware('auth');
Route::get('statusdone', 'OrdersController@statusDone')->name('orders.statusDone')->middleware('auth');
Route::get('statuscancel', 'OrdersController@statusCancel')->name('orders.statusCancel')->middleware('auth');
// Route::get('backPage', 'OrdersController@backPage')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::get('orders/edit/{id}','OrdersController@edit')->name('order.edit');


// Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::get('/home',[
    'uses'=>'HomeController@index',
    'as'=>'home',
    
            ]);

 Route::resource('orders', 'OrdersController')->middleware('auth');

 Route::get('orders/changestatus/{cid}/{sid}', 'OrdersController@changeStatus')->name('orders.changestatus')->middleware('auth');

//  Route::post('/backPage', function () {
//     // Validate the request...

//     return back()->withInput();
// });


            
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/home.blade.php
@extends('layouts.sidebar')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    Hello <b>{{$user->name}}</b>,
                   are logged in!
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/viewww.blade.php
@extends('layouts.sidebar')

@section('title','Orders')

@section('content')

@if(Session::has('notallowed'))
<div class='alert alert-danger'>
    {{Session::get('notallowed')}}
</div>

@endif
         @if (Session::has('message'))
            <div class="alert alert-success">{{Session::get('message')}} </div>
        @endif

    
    @if (Request::is('myOrders')) 
        <h1 title='My order' style="float: left;"><b>My Orders</b></h1> 
        <h1 title='Add a new order' style="float: right;"><b><a href="{{ url('orders/create') }}">+</a></b></h1> 
        <br></br>
        <br></br>
        <h6><a  href="{{action('OrdersController@index')}}">Show All Orders</a></h6>   
    @else
        <h1 title='All order' style="float: left;"><b>All Orders</b></h1>
        <h1 title='Add a new order' style="float: right;"><b><a href="{{ url('orders/create') }}">+</a></b></h1>
        <br></br>
        <br></br>
        <h6><a href="{{ url('myOrders') }}">Show My Orders</a></h6>

    @endif
  
    

    <!-- <div class="panel-heading">
@if (Request::is('myOrders')) 
<h3 class="panel-title" >My Orders</h3>
@endif
</div> -->
    <div class="table-responsive">
    <table class="table align-items-center table-flush" >
            <tr>
            <th>Id</th><th>Seller</th><th>Customer</th><th>Product</th><th>Engine Code</th><th>Address</th><th>Price</th><th>Total Price</th><th>Is Paid?</th><th>Delivery Date</th><th>Status Order</th><th>Edit</th><th>More Details</th>
              
            </tr>
        <!-- the table data -->
            @foreach($orders as $order)
                   
            <tr>
            <td> {{$order->id}}</td>
            <td>
                <div class="dropdown">
                    <!-- <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        @if(isset($order->user_id))
                          {{$order->owner->name}}  
                        @else
                          Assign owner
                        @endif
                    </button>
                  
                  </div> 
            </td>  
            <td>{{$order->customer}}</td>             
            <td> @if(isset($order->product_id))
                          {{$order->own->name}}  
                        @else
                          Assign own
                        @endif</td>
            <td> {{$order->model}}</td> 
            <td> {{$order->address}}</td>
            <td> {{$order->totalPrice}}</td>
            <td> {{$order->totalPrice * 1.17}}</td>
            <td> {{$order->isPaid}}
            <td> {{$order->deliveryDate}}</td>
            <td>
                <div class="dropdown">
                    @if (null != App\Models\Status::next($order->status_id))    
                    <button class="dropdown-toggle" style="background:#99e6e6" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if (isset($order->status_id))
                           {{$order->status->name}}
                        @else
                            Define status
                        @endif
                    </button>
                    @else 
                    {{$order->status->name}}
                    @endif
                                                   
                    @if (App\Models\Status::next($order->status_id) != null )
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach(App\Models\Status::next($order->status_id) as $status)
                         <a class="dropdown-item" href="{{route('orders.changestatus', [$order->id,$status->id])}}">{{$status->name}}</a>
                        @endforeach                               
                    </div>
                    @endif
                </div>                            
            </td>
            <td><a class="badge badge-info " style="background:#99e6e6" href = "{{route('orders.edit',$order->id)}}">Edit</a></td>
            <td> <a class="badge badge-info " style="background:#99e6e6" href="{{ route('orders.show',$order->id) }}"> Click Here </a> </td>
           

        </tr>
            @endforeach
    </table>

    {{$orders->links()}}
@endsection